version: '2'

services:
  usermanagenment:
    image: 'bitnami/postgresql:latest'
    restart: unless-stopped
    ports:
      - 15432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=user
      - POSTGRESQL_DATABASE=user_db
  productmanagenment:
    image: 'bitnami/postgresql:latest'
    restart: unless-stopped
    ports:
      - 15433:5432
    environment:
      - POSTGRESQL_USERNAME=product
      - POSTGRESQL_PASSWORD=product
      - POSTGRESQL_DATABASE=product_db
  ordermanagenment:
    image: 'bitnami/postgresql:latest'
    restart: unless-stopped
    ports:
      - 15434:5432
    environment:
      - POSTGRESQL_USERNAME=order
      - POSTGRESQL_PASSWORD=order
      - POSTGRESQL_DATABASE=order_db
