eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: profilemanagement
          predicates:
            - Path=/**
          filters:
            - RewritePath=/profile, /
          uri: lb://PROFILEMANAGEMENT

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG