eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-management
          predicates:
            - Path=/user/**
          uri: lb://USER-MANAGEMENT
        - id: order-management
          predicates:
            - Path=/order/**
          uri: lb://ORDER-MANAGEMENT
        - id: product-management
          predicates:
            - Path=/product/**
          uri: lb://PRODUCT-MANAGEMENT

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG